### PR TITLE
Explained feature

### PR DESCRIPTION
**Pull request by lukejacksonn**
Implements explained feature with real data from the VTT file located at the url declared under the `explained` key from the episode `index.json` from the CDN.

### Current Behavior:

- If there is no `explained` key in the `index.json` then nothing happens
- If there is an `explained` key then the VTT file is fetch and parsed to JSON with the form
```
{
    title: explained[2],
    youtube: {
      main: explained[3],
      vr: explained[4],
    },
    start: timeToSeconds(explained[1].split(' --> ')[0]),
    end: timeToSeconds(explained[1].split(' --> ')[1])
 }
```
- Every `videoTick` the `explainedOverlay` overly component looks for an item to display
- The overlay will show an item +/- 5 seconds from the specified start time
- The overlay UI shows each item as like..

image

- When the user clicks on the title link or the vr icon then player is paused and the appropriate explained video is opened in a new tab

### CODE REVIEW

**Comment by coltonoscopy** [comment]
Looks great so far! But let's make the following tweaks before we ship?

1. Instead of a component to the top left, let's add a fourth button to the bottom left, beside the ones that are already there, which is grayed out unless an explained segment is available during the video's ticks (no need for thumbnail and title).
2. Let's add an on-hover to all of the buttons that just very briefly explain what they do (including the new one), so our viewers will know what they're clicking (right now it's not super obvious and will become even less so with the introduction of the explained button).
3. The button should hot-load in the explained segment instead of opening a new tab; specifically, if they're watching the regular video, it should open up the regular segment, and if they're watching it in VR, it should open up the VR segment.
4. Once the segment is over for its tick period, it should revert in the player to whichever video they were watching before.

Let me know if you need any more details! Thanks m7!

**Comment by dlloyd09** [comment]
Actually, just chatted with @dmalan. Can we indeed, for point 1., have it be two icons at top left that look very similar to the view modes at bottom left, that only pop up during an Explained segment? One that looks like two talking heads (regular mode, Explained) and one with the same VR goggles as on the regular view modes (VR mode, Explained).

Points 2., 3., and 4. are all exactly right, though!

**Comment by lukejacksonn** [comment]
Thanks for the comments.. just a few questions before diving into an implementation:

> The button should hot-load in the explained segment

We discussed this briefly before and came to the conclusion that overriding the _main_ video would be quite disruptive to the viewing experience (what do we do with all the player chrome, chapters, captions etc. in this instance) but loading an auxiliary player in a similar fashion to the multiscreen experience mode would be a nice middle ground (especially if fullscreen-able)? Which leads into..

> ... specifically, if they're watching the regular video, it should open up the regular segment, and if they're watching it in VR, it should open up the VR segment.

> ...have it be two icons ... one that looks like two talking heads and one with the same VR goggles

Which of these should it be? The former suggests we present the viewer with the explained video in the context of the current experience mode. The latter suggests the viewer has to explicitly choose which video to load. We could probably do both.. preload the auxiliary player in the context of the current experience mode then have a button that lets the viewer toggle between the VR and regular source.

> two icons at top left that  ... only pop up during an Explained segment

The overlay should show for the full duration of the segment? This suggests to me that it would need to be dismissible (which in itself could become quite annoying for the user who just wants to sit back and watch the main video) otherwise it would become quite intrusive on the main video. At the moment the overlay shows 5 seconds either side of the start time which @coltonoscopy hinted was too short of a time, this value was arbitrary and could easily be upped.

Let me know if any of these are exceptionally bad suggestions. Otherwise I will get on and implement such so you can try it out IRL and see how it feels.

**Comment by coltonoscopy** [comment]
Will defer to @dlloyd09 , as it seems spec has changed since last I spoke with @dmalan !

**Comment by dmalan** [comment]
Replied in Asana!

**Comment by dlloyd09** [comment]
@lukejacksonn I think that Colton has now set up at least Week 0's Explained videos with captions in the CDN; is there anything else required at this point for us to test? (The remaining sets of videos are not complete; the transcription service hasn't yet finished.)

CC @coltonoscopy @dcoffey3296 @dmalan

**Comment by coltonoscopy** [comment]
To add to that, @lukejacksonn, I've switched out the VR key in the explained.vtt with the URL leading to the captions for each individual explained segment (since we nixed the VR explained feature), so you can load the captions from the endpoint located there!

**Comment by coltonoscopy** [comment]
Eyy m7! Have a chance to work on? :)

**Comment by lukejacksonn** [comment]
I have been in Thailand for the past week as communicated with @dlloyd09 prior to departure. There was nothing I could do about captions until they existed (which was post departure). Now I am back and the captions are present I can take a look. Will push something up today.

**Comment by lukejacksonn** [comment]
@dmalan @dlloyd09 @coltonoscopy explained captions now show in the explained PiP window if they exist and if the user has closed captions enabled via the main player controls.

**Comment by coltonoscopy** [comment]
@lukejacksonn feel free to merge latest commits into master! Submitted several new issues per a chat I just had with @dmalan and @dlloyd09 ! :) Thanks, m12!

**Pull request merged**
